language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t jwpcassell/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jwpcassell/docker-react npm run test